// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: internal/grpc/proto/subscription.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubscribeRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *UnsubscribeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*SubscriptionItem    `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetSubscriptions() []*SubscriptionItem {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type SubscriptionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Confirmed     bool                   `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	LastSeenTag   string                 `protobuf:"bytes,4,opt,name=last_seen_tag,json=lastSeenTag,proto3" json:"last_seen_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionItem) Reset() {
	*x = SubscriptionItem{}
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionItem) ProtoMessage() {}

func (x *SubscriptionItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionItem.ProtoReflect.Descriptor instead.
func (*SubscriptionItem) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *SubscriptionItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubscriptionItem) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SubscriptionItem) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *SubscriptionItem) GetLastSeenTag() string {
	if x != nil {
		return x.LastSeenTag
	}
	return ""
}

var File_internal_grpc_proto_subscription_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_subscription_proto_rawDesc = "" +
	"\n" +
	"&internal/grpc/proto/subscription.proto\x12\fsubscription\"<\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"-\n" +
	"\x11SubscribeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\x0eConfirmRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"+\n" +
	"\x0fConfirmResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"*\n" +
	"\x12UnsubscribeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"/\n" +
	"\x13UnsubscribeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"#\n" +
	"\vListRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"T\n" +
	"\fListResponse\x12D\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1e.subscription.SubscriptionItemR\rsubscriptions\"~\n" +
	"\x10SubscriptionItem\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1c\n" +
	"\tconfirmed\x18\x03 \x01(\bR\tconfirmed\x12\"\n" +
	"\rlast_seen_tag\x18\x04 \x01(\tR\vlastSeenTag2\xcb\x02\n" +
	"\x13SubscriptionService\x12L\n" +
	"\tSubscribe\x12\x1e.subscription.SubscribeRequest\x1a\x1f.subscription.SubscribeResponse\x12F\n" +
	"\aConfirm\x12\x1c.subscription.ConfirmRequest\x1a\x1d.subscription.ConfirmResponse\x12R\n" +
	"\vUnsubscribe\x12 .subscription.UnsubscribeRequest\x1a!.subscription.UnsubscribeResponse\x12J\n" +
	"\x11ListSubscriptions\x12\x19.subscription.ListRequest\x1a\x1a.subscription.ListResponseB-Z+github-release-notifier/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_subscription_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_subscription_proto_rawDescData []byte
)

func file_internal_grpc_proto_subscription_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_subscription_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_subscription_proto_rawDesc), len(file_internal_grpc_proto_subscription_proto_rawDesc)))
	})
	return file_internal_grpc_proto_subscription_proto_rawDescData
}

var file_internal_grpc_proto_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_grpc_proto_subscription_proto_goTypes = []any{
	(*SubscribeRequest)(nil),    // 0: subscription.SubscribeRequest
	(*SubscribeResponse)(nil),   // 1: subscription.SubscribeResponse
	(*ConfirmRequest)(nil),      // 2: subscription.ConfirmRequest
	(*ConfirmResponse)(nil),     // 3: subscription.ConfirmResponse
	(*UnsubscribeRequest)(nil),  // 4: subscription.UnsubscribeRequest
	(*UnsubscribeResponse)(nil), // 5: subscription.UnsubscribeResponse
	(*ListRequest)(nil),         // 6: subscription.ListRequest
	(*ListResponse)(nil),        // 7: subscription.ListResponse
	(*SubscriptionItem)(nil),    // 8: subscription.SubscriptionItem
}
var file_internal_grpc_proto_subscription_proto_depIdxs = []int32{
	8, // 0: subscription.ListResponse.subscriptions:type_name -> subscription.SubscriptionItem
	0, // 1: subscription.SubscriptionService.Subscribe:input_type -> subscription.SubscribeRequest
	2, // 2: subscription.SubscriptionService.Confirm:input_type -> subscription.ConfirmRequest
	4, // 3: subscription.SubscriptionService.Unsubscribe:input_type -> subscription.UnsubscribeRequest
	6, // 4: subscription.SubscriptionService.ListSubscriptions:input_type -> subscription.ListRequest
	1, // 5: subscription.SubscriptionService.Subscribe:output_type -> subscription.SubscribeResponse
	3, // 6: subscription.SubscriptionService.Confirm:output_type -> subscription.ConfirmResponse
	5, // 7: subscription.SubscriptionService.Unsubscribe:output_type -> subscription.UnsubscribeResponse
	7, // 8: subscription.SubscriptionService.ListSubscriptions:output_type -> subscription.ListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_subscription_proto_init() }
func file_internal_grpc_proto_subscription_proto_init() {
	if File_internal_grpc_proto_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_subscription_proto_rawDesc), len(file_internal_grpc_proto_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_subscription_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_subscription_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_subscription_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_subscription_proto = out.File
	file_internal_grpc_proto_subscription_proto_goTypes = nil
	file_internal_grpc_proto_subscription_proto_depIdxs = nil
}
