// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: confirmation/v1/confirmation.proto

package confirmationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendConfirmationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	ConfirmUrl    string                 `protobuf:"bytes,3,opt,name=confirm_url,json=confirmUrl,proto3" json:"confirm_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendConfirmationRequest) Reset() {
	*x = SendConfirmationRequest{}
	mi := &file_confirmation_v1_confirmation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendConfirmationRequest) ProtoMessage() {}

func (x *SendConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_confirmation_v1_confirmation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendConfirmationRequest.ProtoReflect.Descriptor instead.
func (*SendConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_confirmation_v1_confirmation_proto_rawDescGZIP(), []int{0}
}

func (x *SendConfirmationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendConfirmationRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SendConfirmationRequest) GetConfirmUrl() string {
	if x != nil {
		return x.ConfirmUrl
	}
	return ""
}

type SendConfirmationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendConfirmationResponse) Reset() {
	*x = SendConfirmationResponse{}
	mi := &file_confirmation_v1_confirmation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendConfirmationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendConfirmationResponse) ProtoMessage() {}

func (x *SendConfirmationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_confirmation_v1_confirmation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendConfirmationResponse.ProtoReflect.Descriptor instead.
func (*SendConfirmationResponse) Descriptor() ([]byte, []int) {
	return file_confirmation_v1_confirmation_proto_rawDescGZIP(), []int{1}
}

var File_confirmation_v1_confirmation_proto protoreflect.FileDescriptor

const file_confirmation_v1_confirmation_proto_rawDesc = "" +
	"\n" +
	"\"confirmation/v1/confirmation.proto\x12\x0fconfirmation.v1\"d\n" +
	"\x17SendConfirmationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1f\n" +
	"\vconfirm_url\x18\x03 \x01(\tR\n" +
	"confirmUrl\"\x1a\n" +
	"\x18SendConfirmationResponse2~\n" +
	"\x13ConfirmationService\x12g\n" +
	"\x10SendConfirmation\x12(.confirmation.v1.SendConfirmationRequest\x1a).confirmation.v1.SendConfirmationResponseBGZEgithub-release-notifier/notifier/proto/confirmation/v1;confirmationv1b\x06proto3"

var (
	file_confirmation_v1_confirmation_proto_rawDescOnce sync.Once
	file_confirmation_v1_confirmation_proto_rawDescData []byte
)

func file_confirmation_v1_confirmation_proto_rawDescGZIP() []byte {
	file_confirmation_v1_confirmation_proto_rawDescOnce.Do(func() {
		file_confirmation_v1_confirmation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_confirmation_v1_confirmation_proto_rawDesc), len(file_confirmation_v1_confirmation_proto_rawDesc)))
	})
	return file_confirmation_v1_confirmation_proto_rawDescData
}

var file_confirmation_v1_confirmation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_confirmation_v1_confirmation_proto_goTypes = []any{
	(*SendConfirmationRequest)(nil),  // 0: confirmation.v1.SendConfirmationRequest
	(*SendConfirmationResponse)(nil), // 1: confirmation.v1.SendConfirmationResponse
}
var file_confirmation_v1_confirmation_proto_depIdxs = []int32{
	0, // 0: confirmation.v1.ConfirmationService.SendConfirmation:input_type -> confirmation.v1.SendConfirmationRequest
	1, // 1: confirmation.v1.ConfirmationService.SendConfirmation:output_type -> confirmation.v1.SendConfirmationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_confirmation_v1_confirmation_proto_init() }
func file_confirmation_v1_confirmation_proto_init() {
	if File_confirmation_v1_confirmation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_confirmation_v1_confirmation_proto_rawDesc), len(file_confirmation_v1_confirmation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_confirmation_v1_confirmation_proto_goTypes,
		DependencyIndexes: file_confirmation_v1_confirmation_proto_depIdxs,
		MessageInfos:      file_confirmation_v1_confirmation_proto_msgTypes,
	}.Build()
	File_confirmation_v1_confirmation_proto = out.File
	file_confirmation_v1_confirmation_proto_goTypes = nil
	file_confirmation_v1_confirmation_proto_depIdxs = nil
}
