// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: confirmation/v1/confirmation.proto

package confirmationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfirmationService_SendConfirmation_FullMethodName = "/confirmation.v1.ConfirmationService/SendConfirmation"
)

// ConfirmationServiceClient is the client API for ConfirmationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfirmationService sends subscription confirmation emails on behalf of the
// subscribe-saga orchestrator. It is the gRPC sibling of the REST
// POST /internal/confirmations endpoint (ADR-0007, ADR-0008).
type ConfirmationServiceClient interface {
	// SendConfirmation renders and sends one confirmation email. It returns
	// OK on success and a non-OK status (e.g. UNAVAILABLE) when the email
	// backend fails, so the orchestrator can compensate.
	SendConfirmation(ctx context.Context, in *SendConfirmationRequest, opts ...grpc.CallOption) (*SendConfirmationResponse, error)
}

type confirmationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfirmationServiceClient(cc grpc.ClientConnInterface) ConfirmationServiceClient {
	return &confirmationServiceClient{cc}
}

func (c *confirmationServiceClient) SendConfirmation(ctx context.Context, in *SendConfirmationRequest, opts ...grpc.CallOption) (*SendConfirmationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendConfirmationResponse)
	err := c.cc.Invoke(ctx, ConfirmationService_SendConfirmation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfirmationServiceServer is the server API for ConfirmationService service.
// All implementations must embed UnimplementedConfirmationServiceServer
// for forward compatibility.
//
// ConfirmationService sends subscription confirmation emails on behalf of the
// subscribe-saga orchestrator. It is the gRPC sibling of the REST
// POST /internal/confirmations endpoint (ADR-0007, ADR-0008).
type ConfirmationServiceServer interface {
	// SendConfirmation renders and sends one confirmation email. It returns
	// OK on success and a non-OK status (e.g. UNAVAILABLE) when the email
	// backend fails, so the orchestrator can compensate.
	SendConfirmation(context.Context, *SendConfirmationRequest) (*SendConfirmationResponse, error)
	mustEmbedUnimplementedConfirmationServiceServer()
}

// UnimplementedConfirmationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfirmationServiceServer struct{}

func (UnimplementedConfirmationServiceServer) SendConfirmation(context.Context, *SendConfirmationRequest) (*SendConfirmationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendConfirmation not implemented")
}
func (UnimplementedConfirmationServiceServer) mustEmbedUnimplementedConfirmationServiceServer() {}
func (UnimplementedConfirmationServiceServer) testEmbeddedByValue()                             {}

// UnsafeConfirmationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfirmationServiceServer will
// result in compilation errors.
type UnsafeConfirmationServiceServer interface {
	mustEmbedUnimplementedConfirmationServiceServer()
}

func RegisterConfirmationServiceServer(s grpc.ServiceRegistrar, srv ConfirmationServiceServer) {
	// If the following call panics, it indicates UnimplementedConfirmationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfirmationService_ServiceDesc, srv)
}

func _ConfirmationService_SendConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfirmationServiceServer).SendConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfirmationService_SendConfirmation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfirmationServiceServer).SendConfirmation(ctx, req.(*SendConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfirmationService_ServiceDesc is the grpc.ServiceDesc for ConfirmationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfirmationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "confirmation.v1.ConfirmationService",
	HandlerType: (*ConfirmationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendConfirmation",
			Handler:    _ConfirmationService_SendConfirmation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "confirmation/v1/confirmation.proto",
}
